function(ran_apply_project_warnings target_name)
  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    target_compile_options(${target_name} PRIVATE -Wall -Wextra -Wpedantic)
  elseif(MSVC)
    target_compile_options(${target_name} PRIVATE /W4)
  endif()
endfunction()

function(ran_apply_sanitizers target_name)
  if(NOT RAN_ENABLE_SANITIZERS)
    return()
  endif()

  if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
    target_compile_options(${target_name} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
    target_link_options(${target_name} PRIVATE -fsanitize=address,undefined)
  else()
    message(WARNING "RAN_ENABLE_SANITIZERS is only configured for GCC and Clang.")
  endif()
endfunction()
